FROM nginx:stable-alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY fullchain.pem /etc/letsencrypt/live/j6b107.p.ssafy.io/fullchain.pem
COPY privkey.pem /etc/letsencrypt/live/j6b107.p.ssafy.io/privkey.pem
