server:
  port: 80

spring:
  datasource:
    url: jdbc-url
    driver-class-name: jdbc driver name
    hikari:
      username: client id
      password: client password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: dialect
        show_sql: true
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  config:
    activate:
      on-profile: prod
